version: '3.4'

services:
  samba:
    image: lumoc/samba
    environment:
      TZ: 'Europe/Berlin'
    networks:
      - default
    read_only: true
    tmpfs:
      - /tmp
    restart: unless-stopped
    stdin_open: true
    tty: true
    volumes:
      - /mnt:/mnt:z
    command: '-s "Mount;/mnt"'

networks:
  default:
